# Generated by Django 2.0.1 on 2018-03-11 16:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title, created'),
        ),
    ]
