# Generated by Django 2.0.1 on 2018-03-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20180311_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
