# Generated by Django 3.0.4 on 2020-03-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180315_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infocard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='InfocardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='pictures/', verbose_name='img')),
                ('infocard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.Infocard')),
            ],
        ),
    ]
