# Generated by Django 3.0.4 on 2020-04-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_infocard_infocardimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='content_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='content_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='description_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='description_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
